<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Shopping.Infra\Shopping.Infra.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include=".github\workflows\deploy.yml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dad9f652-91e8-4194-b894-ef0ababe148d</UserSecretsId>
  </PropertyGroup>

</Project>
